name : call API with cron
on :
  schedule:
    - cron: '0/20 * * * *'
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: curl -L 'https://api.nweoo.com/news/articles'
